[project]
name = "mcp-updated"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Niks056", email = "gnikita476@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langchain-groq>=1.1.3",
    "langchain-mcp-adapters>=0.3.2",
    "langgraph>=1.2.14",
    "mcp>=1.30.0",
]

[project.scripts]
mcp-updated = "mcp_updated:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
